/**
 * Units
 *
 * @type {Object}
 */
export const Units = {
  bpm: 'bpm',
  calorie: 'calorie',
  celsius: 'celsius',
  count: 'count',
  day: 'day',
  fahrenheit: 'fahrenheit',
  foot: 'foot',
  gram: 'gram',
  hour: 'hour',
  inch: 'inch',
  joule: 'joule',
  kilocalorie: 'kilocalorie',
  meter: 'meter',
  mgPerdL: 'mgPerdL',
  mile: 'mile',
  minute: 'minute',
  mmhg: 'mmhg',
  mmolPerL: 'mmolPerL',
  percent: 'percent',
  pound: 'pound',
  second: 'second',
  mlPerKgMin: 'mlPerKgMin',
  literPerMinute: 'literPerMinute',
  kilometer: 'kilometer',
  liter: 'liter',
  milliliter: 'milliliter',
  milligram: 'milligram',
  microgram: 'microgram',
  watt: 'watt',
  rpm: 'rpm',
  meterPerSecond: 'meterPerSecond',
  kmPerHour: 'kmPerHour',
  milePerHour: 'milePerHour',
  kcalPerKgHour: 'kcalPerKgHour',
  decibel: 'decibel',
  microsiemens: 'microsiemens',
  appleEffortScore: 'appleEffortScore',
}
